We have to build it inside alpine because glibc vs musl.
Signed-off-by: Johnathan Falk <johnathan.falk@gmail.com>

diff --git a/.github/workflows/standalone.yml b/.github/workflows/standalone.yml
--- a/.github/workflows/standalone.yml
+++ b/.github/workflows/standalone.yml
@@ -37,21 +37,21 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Cache node_modules
-        uses: actions/cache@v4
-        with:
-          path: "${{ env.UI_DIRECTORY }}/node_modules"
-          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: ${{ runner.os }}-modules-
+      # - name: Cache node_modules
+      #   uses: actions/cache@v4
+      #   with:
+      #     path: "${{ env.UI_DIRECTORY }}/node_modules"
+      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
+      #     restore-keys: ${{ runner.os }}-modules-
 
-      - name: Setup NodeJS
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: "${{ env.UI_DIRECTORY }}/.nvmrc"
+      # - name: Setup NodeJS
+      #   uses: actions/setup-node@v4
+      #   with:
+      #     node-version-file: "${{ env.UI_DIRECTORY }}/.nvmrc"
 
-      - name: Install dependencies
-        run: npm install
-        working-directory: ${{ env.UI_DIRECTORY }}
+      # - name: Install dependencies
+      #   run: npm install
+      #   working-directory: ${{ env.UI_DIRECTORY }}
 
       # - name: Check Types
       #   run: npm run check:ts
@@ -73,39 +73,39 @@ jobs:
       #   run: npm run build:ci
       #   working-directory: ${{ env.UI_DIRECTORY }}
 
-      - name: Install uv
-        uses: astral-sh/setup-uv@v5
-        with:
-          version: "0.5.15"  # Best practice: pin uv version
-          enable-cache: true
-          cache-dependency-glob: "uv.lock"
+      # - name: Install uv
+      #   uses: astral-sh/setup-uv@v5
+      #   with:
+      #     version: "0.5.15"  # Best practice: pin uv version
+      #     enable-cache: true
+      #     cache-dependency-glob: "uv.lock"
 
-      - name: Set up Python
-        run: uv python install python3.10
+      # - name: Set up Python
+      #   run: uv python install python3.10
 
-      - name: Install the project
-        run: uv sync --all-extras --dev --index https://wheel-index.linuxserver.io/alpine-3.21/
+      # - name: Install the project
+      #   run: uv sync --all-extras --dev --index https://wheel-index.linuxserver.io/alpine-3.21/
 
-      - name: uv build
-        run: uv build --index https://wheel-index.linuxserver.io/alpine-3.21/
+      # - name: uv build
+      #   run: uv build --index https://wheel-index.linuxserver.io/alpine-3.21/
 
-      - name: Unit Tests
-        run: |
-          uv run -- bazarr.py --no-update &
-          PID=$!
-          sleep 15
-          if kill -s 0 $PID
-          then
-            echo "**** Bazarr launch successful ****"
-            kill $PID
-            exit 0
-          else
-          echo "**** Bazarr launch failed ****"
-            exit 1
-          fi
+      # - name: Unit Tests
+      #   run: |
+      #     uv run -- bazarr.py --no-update &
+      #     PID=$!
+      #     sleep 15
+      #     if kill -s 0 $PID
+      #     then
+      #       echo "**** Bazarr launch successful ****"
+      #       kill $PID
+      #       exit 0
+      #     else
+      #     echo "**** Bazarr launch failed ****"
+      #       exit 1
+      #     fi
 
-      - name: Minimize uv cache
-        run: uv cache prune --ci
+      # - name: Minimize uv cache
+      #   run: uv cache prune --ci
 
       # - name: Export Bazarr Build Info
       #   run: |
@@ -127,6 +127,7 @@ jobs:
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          context: git
           tags: |
             type=raw,value=latest,enable={{is_default_branch}}
             type=schedule,enable=true,priority=1000,prefix=,suffix=,pattern=nightly
